#!/usr/bin/env python3

import os
import subprocess
import time

from optparse import OptionParser

parser = OptionParser(usage="%prog")

parser.add_option("-s", dest="device",
                  help="Specifies a device for adb to connect to")

(options, args) = parser.parse_args()

adb = ["adb"]
if options.device:
    adb = ["adb", "-s", options.device]

out = "out_" + time.strftime("%Y%m%d_%H%M%S")

p = subprocess.Popen(adb + ["logcat", "-g", "-b", "all"], stdout=subprocess.PIPE)
o, e = p.communicate()
lines = o.decode().splitlines()

if not os.path.exists(out): os.makedirs(out)

for line in lines:
    name = line.split(":")[0]
    subprocess.call(adb + ["logcat", "-v", "time", "-b", name, "-d"],
                    stdout=open("{}/{}.log".format(out, name), "w"))

subprocess.call(adb + ["shell", "dmesg"],
                stdout=open("{}/dmesg.log".format(out), "w"))

subprocess.call(adb + ["shell", "dumpsys"],
                stdout=open("{}/dumpsys.log".format(out), "w"))
